/**
 * Auto-generated TypeScript definitions for i18n translations
 * Generated from: app/locales/en/*.json
 * DO NOT EDIT THIS FILE MANUALLY - Run 'bun run generate:i18n-types' or 'npm run generate:i18n-types' to regenerate
 * 
 * Type-safe translation system with full IntelliSense support
 * Supports generic type inference and static type checking
 */

/**
 * Translations for about namespace
 * Generated from: app/locales/en/about.json
 */
export interface AboutTranslations {
  meta: {
    title: string;
    description: string;
  };
  heading: string;
  tagline: string;
  taglineSecond: string;
  description: string;
  descriptionSecond: string;
  contactLabel: string;
}

/**
 * Translations for admin namespace
 * Generated from: app/locales/en/admin.json
 */
export interface AdminTranslations {
  meta: {
    title: string;
    description: string;
  };
  title: string;
  subtitle: string;
  systemStatus: {
    title: string;
    description: string;
    database: string;
    authentication: string;
    sessions: string;
    status: {
      online: string;
      active: string;
      healthy: string;
    };
  };
  userManagement: {
    title: string;
    description: string;
    viewAllUsers: string;
    createNewUser: string;
    manageRoles: string;
  };
  security: {
    title: string;
    description: string;
    sessionManagement: string;
    accessLogs: string;
    securitySettings: string;
  };
  roleBasedAccess: {
    title: string;
    description: string;
    requirements: {
      title: string;
      authenticated: string;
      adminRole: string;
      routeLevel: string;
      forbidden: string;
    };
    accessGranted: {
      title: string;
      message: string;
    };
    actions: {
      userDashboard: string;
      returnHome: string;
    };
  };
  errors: {
    userNotFound: string;
  };
}

/**
 * Translations for auth namespace
 * Generated from: app/locales/en/auth.json
 */
export interface AuthTranslations {
  login: {
    title: string;
    description: string;
    form: {
      email: {
        label: string;
        placeholder: string;
      };
      password: {
        label: string;
        placeholder: string;
      };
      submit: string;
      submitting: string;
    };
    validation: {
      emailRequired: string;
      passwordMinLength: string;
    };
    noAccount: string;
    signUpLink: string;
  };
  register: {
    title: string;
    description: string;
    form: {
      name: {
        label: string;
        placeholder: string;
      };
      email: {
        label: string;
        placeholder: string;
      };
      password: {
        label: string;
        placeholder: string;
      };
      confirmPassword: {
        label: string;
        placeholder: string;
      };
      submit: string;
      submitting: string;
    };
    validation: {
      nameMinLength: string;
      emailRequired: string;
      passwordMinLength: string;
      confirmPasswordRequired: string;
      passwordsDoNotMatch: string;
    };
    errors: {
      accountExists: string;
    };
    hasAccount: string;
    signInLink: string;
  };
  verifyEmail: {
    title: string;
    description: string;
    success: {
      title: string;
      message: string;
      goToSignIn: string;
    };
    error: {
      title: string;
      backToSignIn: string;
    };
    validation: {
      tokenRequired: string;
    };
    errors: {
      somethingWentWrong: string;
      invalidToken: string;
      expiredToken: string;
      alreadyVerified: string;
      tokenNotFound: string;
      databaseError: string;
    };
  };
  forgotPassword: {
    title: string;
    description: string;
    heading: string;
    subheading: string;
    emailLabel: string;
    emailPlaceholder: string;
    submitButton: string;
    backToSignIn: string;
    successHeading: string;
    successSubheading: string;
    successMessage: string;
    errorInvalidEmail: string;
    errorGeneral: string;
  };
  resetPassword: {
    title: string;
    description: string;
    heading: string;
    subheading: string;
    passwordLabel: string;
    passwordPlaceholder: string;
    confirmPasswordLabel: string;
    confirmPasswordPlaceholder: string;
    submitButton: string;
    backToSignIn: string;
    passwordRequirements: string;
    requirementLength: string;
    requirementUppercase: string;
    requirementLowercase: string;
    requirementNumber: string;
    requirementSpecial: string;
    errorMissingToken: string;
    errorPasswordTooShort: string;
    errorConfirmPasswordMissing: string;
    errorPasswordsDoNotMatch: string;
    errorWeakPassword: string;
    errorInvalidToken: string;
    errorGeneral: string;
    submitting: string;
  };
  common: {
    agreementText: string;
    termsOfService: string;
    privacyPolicy: string;
    and: string;
  };
}

/**
 * Translations for blog namespace
 * Generated from: app/locales/en/blog.json
 */
export interface BlogTranslations {
  meta: {
    title: string;
    description: string;
  };
  home: {
    title: string;
    subtitle: string;
    noPosts: string;
  };
  card: {
    by: string;
    readMore: string;
  };
  error: {
    notFoundTitle: string;
    serverErrorTitle: string;
    notFoundMessage: string;
    serverErrorMessage: string;
    errorDetails: string;
    viewAllPosts: string;
    goHome: string;
  };
  loading: {
    title: string;
    description: string;
    cancel: string;
  };
}

/**
 * Translations for calendar namespace
 * Generated from: app/locales/en/calendar.json
 */
export interface CalendarTranslations {
  meta: {
    title: string;
    description: string;
  };
  common: {
    today: string;
    nextMonth: string;
    previousMonth: string;
  };
}

/**
 * Translations for common namespace
 * Generated from: app/locales/en/common.json
 */
export interface CommonTranslations {
  loading: string;
  error: string;
  notFound: string;
  back: string;
  next: string;
  previous: string;
  submit: string;
  cancel: string;
  save: string;
  edit: string;
  delete: string;
  close: string;
  open: string;
  search: string;
  filter: string;
  sort: string;
  language: string;
}

/**
 * Translations for dashboard namespace
 * Generated from: app/locales/en/dashboard.json
 */
export interface DashboardTranslations {
  meta: {
    title: string;
    description: string;
  };
  welcome: {
    title: string;
    subtitle: string;
  };
  userInfo: {
    title: string;
    description: string;
    fields: {
      name: string;
      email: string;
      role: string;
      memberSince: string;
    };
  };
  quickActions: {
    title: string;
    description: string;
    actions: {
      editProfile: string;
      settings: string;
      viewAnalytics: string;
      adminPanel: string;
    };
  };
  stats: {
    daysActive: {
      title: string;
      subtitle: string;
    };
    totalLogins: {
      title: string;
      subtitle: string;
    };
    profileViews: {
      title: string;
      subtitle: string;
    };
    lastLogin: {
      title: string;
      subtitle: string;
    };
  };
  recentActivity: {
    title: string;
    description: string;
    noActivity: string;
    types: {
      login: string;
      profileUpdate: string;
      profileUpdated: string;
      passwordChange: string;
      settingsChange: string;
      settingsChanged: string;
      accountCreated: string;
    };
  };
  systemStatus: {
    title: string;
    description: string;
    uptime: string;
    responseTime: string;
    activeUsers: string;
    status: {
      operational: string;
      degraded: string;
      outage: string;
    };
  };
  authDemo: {
    title: string;
    description: string;
    content: string;
    features: {
      secureAuth: string;
      userDatabase: string;
      sessionManagement: string;
      roleBasedAccess: string;
      activityTracking: string;
      statisticsCalculation: string;
    };
    actions: {
      home: string;
      learnMore: string;
    };
  };
}

/**
 * Translations for errors namespace
 * Generated from: app/locales/en/errors.json
 */
export interface ErrorsTranslations {
  pageNotFound: string;
  unexpectedError: string;
  goHome: string;
  tryAgain: string;
  common: {
    checkInput: string;
    somethingWentWrong: string;
  };
}

/**
 * Translations for forest namespace
 * Generated from: app/locales/en/forest.json
 */
export interface ForestTranslations {
  meta: {
    title: string;
    description: string;
  };
  screens: {
    planting: {
      slogan: string;
    };
    growing: {
      slogans: {
        growing_1: string;
        growing_2: string;
        growing_3: string;
        growing_4: string;
        growing_5: string;
      };
    };
    full_grown: {
      slogan: string;
    };
    withered: {
      slogan: string;
    };
  };
  actions: {
    start: string;
    give: string;
    take_break: string;
  };
  common: {
    work: string;
  };
}

/**
 * Translations for landing namespace
 * Generated from: app/locales/en/landing.json
 */
export interface LandingTranslations {
  title: string;
  subtitle: string;
  description: string;
  getStarted: string;
  viewDocs: string;
  hero: {
    badge: string;
    title: string;
    subtitle: string;
    description: string;
    starOnGitHub: string;
    quickStart: string;
    statusText: string;
  };
  features: {
    title: string;
    badge: string;
    sectionTitle: string;
    sectionDescription: string;
    typeSafety: {
      title: string;
      description: string;
    };
    performance: {
      title: string;
      description: string;
    };
    developerErgonomics: {
      title: string;
      description: string;
    };
    versatile: {
      title: string;
      description: string;
    };
    typeScript: string;
    typeScriptDesc: string;
    reactRouter: string;
    reactRouterDesc: string;
    cloudflare: string;
    cloudflareDesc: string;
    database: string;
    databaseDesc: string;
    ui: string;
    uiDesc: string;
    testing: string;
    testingDesc: string;
  };
  gettingStarted: {
    badge: string;
    title: string;
    description: string;
    steps: {
      clone: {
        title: string;
        description: string;
        note: string;
      };
      install: {
        title: string;
        description: string;
        note: string;
      };
      database: {
        title: string;
        description: string;
        note: string;
      };
      start: {
        title: string;
        description: string;
        note: string;
      };
    };
    copyCommand: string;
    copied: string;
    setupTime: string;
  };
  footer: {
    tagline: string;
    copyright: string;
  };
  builtForDevelopers: {
    badge: string;
    title: string;
    stats: {
      setupTime: {
        value: string;
        label: string;
        description: string;
      };
      typeSafe: {
        value: string;
        label: string;
        description: string;
      };
      configHeadaches: {
        value: string;
        label: string;
        description: string;
      };
    };
  };
  license: {
    badge: string;
    title: string;
    openSource: {
      badge: string;
      price: string;
      title: string;
      description: string;
      features: {
        useFreely: string;
        fullSource: string;
        mustOpenSource: string;
      };
      button: string;
    };
    commercial: {
      badge: string;
      price: string;
      title: string;
      description: string;
      features: {
        noOpenSource: string;
        oneTime: string;
        gumroad: string;
      };
      button: string;
      comingSoon: string;
    };
  };
  showcase: {
    title: string;
    description: string;
    builtInDemos: {
      title: string;
      description: string;
    };
    communityShowcases: {
      title: string;
      description: string;
    };
    demos: {
      charts: {
        name: string;
        description: string;
        tags: string;
      };
      calendar: {
        name: string;
        description: string;
        tags: string;
      };
      forest: {
        name: string;
        description: string;
        tags: string;
      };
      blog: {
        name: string;
        description: string;
        tags: string;
      };
      qrGenerator: {
        name: string;
        description: string;
        tags: string;
      };
    };
  };
  techStack: {
    badge: string;
    title: string;
    description: string;
  };
  github: {
    seeMore: string;
  };
  donate: {
    label: string;
  };
}

/**
 * Translations for legal namespace
 * Generated from: app/locales/en/legal.json
 */
export interface LegalTranslations {
  terms: {
    title: string;
    description: string;
    lastUpdated: string;
    sections: {
      acceptance: {
        title: string;
        content: string;
      };
      description: {
        title: string;
        content: string;
      };
      responsibilities: {
        title: string;
        content: string;
        items: string;
      };
      intellectual: {
        title: string;
        content: string;
      };
      privacy: {
        title: string;
        content: string;
      };
      liability: {
        title: string;
        content: string;
      };
      changes: {
        title: string;
        content: string;
      };
      contact: {
        title: string;
        content: string;
      };
    };
  };
  privacy: {
    title: string;
    description: string;
    lastUpdated: string;
    sections: {
      collection: {
        title: string;
        content: string;
        personal: {
          title: string;
          items: string;
        };
        usage: {
          title: string;
          items: string;
        };
      };
      usage: {
        title: string;
        content: string;
        items: string;
      };
      sharing: {
        title: string;
        content: string;
        items: string;
      };
      security: {
        title: string;
        content: string;
      };
      retention: {
        title: string;
        content: string;
      };
      rights: {
        title: string;
        content: string;
        items: string;
      };
      cookies: {
        title: string;
        content: string;
      };
      children: {
        title: string;
        content: string;
      };
      policyChanges: {
        title: string;
        content: string;
      };
      contact: {
        title: string;
        content: string;
      };
    };
  };
  common: {
    backToHome: string;
    tableOfContents: string;
    print: string;
    share: string;
    readingTime: string;
    jumpToSection: string;
    related: string;
    scrollToTop: string;
    contactInfo: string;
    officialRepository: string;
    supportChannels: string;
  };
}

/**
 * Translations for navigation namespace
 * Generated from: app/locales/en/navigation.json
 */
export interface NavigationTranslations {
  home: string;
  about: string;
  showcase: string;
  features: string;
  docs: string;
  dashboard: string;
  admin: string;
  signIn: string;
  signUp: string;
  signOut: string;
  menu: string;
  closeMenu: string;
  blog: string;
}

/**
 * Translations for qr-generator namespace
 * Generated from: app/locales/en/qr-generator.json
 */
export interface QrGeneratorTranslations {
  title: string;
  description: string;
  inputLabel: string;
  inputPlaceholder: string;
  sizeLabel: string;
  errorCorrectionLabel: string;
  marginLabel: string;
  yes: string;
  no: string;
  preview: string;
  downloadPNG: string;
  downloadJPG: string;
  emptyState: string;
  maxLengthReached: string;
}

/**
 * Translations for showcase namespace
 * Generated from: app/locales/en/showcase.json
 */
export interface ShowcaseTranslations {
  title: string;
  backToHome: string;
  scrollToTop: string;
  viewProject: string;
  showcase: {
    title: string;
    description: string;
    components: string;
    examples: string;
    demos: string;
  };
  emptyTitle: string;
  emptyMessage: string;
}

/**
 * Translations for theme namespace
 * Generated from: app/locales/en/theme.json
 */
export interface ThemeTranslations {
  light: string;
  dark: string;
  system: string;
  toggle: string;
}

/**
 * Translations for time namespace
 * Generated from: app/locales/en/time.json
 */
export interface TimeTranslations {
  now: string;
  minutesAgo: string;
  minutesAgo_other: string;
  hoursAgo: string;
  hoursAgo_other: string;
  daysAgo: string;
  daysAgo_other: string;
  weeksAgo: string;
  weeksAgo_other: string;
  monthsAgo: string;
  monthsAgo_other: string;
  yearsAgo: string;
  yearsAgo_other: string;
}

/**
 * Complete namespace translation structure combining all translation namespaces
 * Provides full static typing for all translation keys
 */
export type NamespaceTranslations = CommonTranslations & {
  about: AboutTranslations;
  admin: AdminTranslations;
  auth: AuthTranslations;
  blog: BlogTranslations;
  calendar: CalendarTranslations;
  dashboard: DashboardTranslations;
  errors: ErrorsTranslations;
  forest: ForestTranslations;
  landing: LandingTranslations;
  legal: LegalTranslations;
  navigation: NavigationTranslations;
  qrGenerator: QrGeneratorTranslations;
  showcase: ShowcaseTranslations;
  theme: ThemeTranslations;
  time: TimeTranslations;
};

/**
 * Type-safe key path helper for translation keys
 * Provides IntelliSense support for nested translation keys
 */
export type TranslationKeyPath<T extends object> = {
  [K in keyof T]: T[K] extends object
    ? `${K & string}.${TranslationKeyPath<T[K]>}`
    : K;
}[keyof T];

/**
 * Generic translation provider with static type support
 */
export type TranslationProvider<T extends NamespaceTranslations = NamespaceTranslations> = {
  get<K extends TranslationKeyPath<T>>(key: K, params?: Record<string, string | number>): string;
  has(key: string): boolean;
};

/**
 * Global ambient type declaration for NamespaceTranslations
 * Available globally without imports
 */
declare global {
  type NamespaceTranslations = NamespaceTranslations;
  type TranslationKeyPath = TranslationKeyPath<NamespaceTranslations>;
}
