// Generated by Wrangler by running `wrangler types`

declare namespace Cloudflare {
	interface Env {
		VALUE_FROM_CLOUDFLARE: "Hello from Cloudflare";
		DB: D1Database;
	}
}
interface Env extends Cloudflare.Env {}
