// Generated by Wrangler by running `wrangler types`

declare namespace Cloudflare {
  interface Env {
    DB: D1Database;
    // Security
    JWT_SECRET: string;
    AUTH_SESSION_SECRET: string;
    ADMIN_REGISTRATION_SECRET: string;
    // Landing page environment variables
    VITE_LANDING_PAGE_TITLE?: string;
    VITE_LANDING_PAGE_DESCRIPTION?: string;
    VITE_LANDING_PAGE_REPOSITORY?: string;
    VITE_LANDING_PAGE_COMMERCIAL_LINK?: string;
  }
}
interface Env extends Cloudflare.Env {}
