/**
 * Auto-generated language constants and types
 * Generated from: packages/i18n-locales/src/locales/*
 * DO NOT EDIT THIS FILE MANUALLY - Run 'bun run generate:i18n-types' to regenerate
 */

/**
 * Supported language codes
 * Auto-generated from available locale directories
 */
export type SupportedLanguage =
  | "ar"
  | "en"
  | "es"
  | "fr"
  | "hi"
  | "ja"
  | "th"
  | "vi"
  | "zh";

export const DEFAULT_LANGUAGE = "en" as const;

export const SUPPORTED_LANGUAGES = [
  "ar",
  "en",
  "es",
  "fr",
  "hi",
  "ja",
  "th",
  "vi",
  "zh",
] as const;
