#!/usr/bin/env bun
/**
 * Generate static TypeScript types from English translation JSON files
 * This script creates type definitions without importing actual JSON files,
 * reducing bundle size in the modular monolith architecture.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const LOCALES_DIR = join(process.cwd(), "app", "locales", "en");
const OUTPUT_FILE = join(
  process.cwd(),
  "app",
  "lib",
  "i18n",
  "types",
  "generated-translations.d.ts",
);

/**
 * Generate TypeScript interface from JSON object recursively
 */
function generateInterfaceFromJson(
  obj: Record<string, unknown>,
  indent = 0,
): string {
  const spaces = "  ".repeat(indent);
  let result = "";

  for (const [key, value] of Object.entries(obj)) {
    if (typeof value === "object" && value !== null && !Array.isArray(value)) {
      result += `${spaces}${key}: {\n`;
      result += generateInterfaceFromJson(
        value as Record<string, unknown>,
        indent + 1,
      );
      result += `${spaces}};\n`;
    } else {
      result += `${spaces}${key}: string;\n`;
    }
  }

  return result;
}

/**
 * Read and parse JSON file
 */
function readJsonFile(filename: string): Record<string, unknown> {
  const filePath = join(LOCALES_DIR, filename);
  const content = readFileSync(filePath, "utf-8");
  return JSON.parse(content) as Record<string, unknown>;
}

/**
 * Generate type definitions for all translation namespaces
 */
function generateTypes(): void {
  console.log("🔄 Generating i18n type definitions...");

  // List of translation namespace files
  const namespaces = [
    "about",
    "admin",
    "auth",
    "blog",
    "calendar",
    "common",
    "dashboard",
    "errors",
    "forest",
    "landing",
    "legal",
    "navigation",
    "qr-generator",
    "showcase",
    "theme",
    "time",
  ];

  let typeDefinitions = `/**
 * Auto-generated TypeScript definitions for i18n translations
 * Generated from: app/locales/en/*.json
 * DO NOT EDIT THIS FILE MANUALLY - Run 'bun run generate:i18n-types' to regenerate
 */

`;

  // Generate individual interfaces for each namespace
  for (const namespace of namespaces) {
    const json = readJsonFile(`${namespace}.json`);
    const interfaceName = `${namespace.charAt(0).toUpperCase()}${namespace.slice(1).replace(/-([a-z])/g, (_, char: string) => char.toUpperCase())}Translations`;

    typeDefinitions += `export interface ${interfaceName} {\n`;
    typeDefinitions += generateInterfaceFromJson(json, 1);
    typeDefinitions += `}\n\n`;
  }

  // Generate the main NamespaceTranslations type
  typeDefinitions += `/**
 * Complete namespace translation structure combining all translation namespaces
 */
export type NamespaceTranslations = CommonTranslations & {
  about: AboutTranslations;
  admin: AdminTranslations;
  auth: AuthTranslations;
  blog: BlogTranslations;
  calendar: CalendarTranslations;
  dashboard: DashboardTranslations;
  errors: ErrorsTranslations;
  forest: ForestTranslations;
  landing: LandingTranslations;
  legal: LegalTranslations;
  navigation: NavigationTranslations;
  qrGenerator: QrGeneratorTranslations;
  showcase: ShowcaseTranslations;
  theme: ThemeTranslations;
  time: TimeTranslations;
};
`;

  // Write the generated types to file
  writeFileSync(OUTPUT_FILE, typeDefinitions, "utf-8");

  console.log(`✅ Generated type definitions at: ${OUTPUT_FILE}`);
  console.log(`📦 Bundle size improvement: No runtime JSON imports in types!`);
}

// Run the type generation
try {
  generateTypes();
} catch (error) {
  console.error("❌ Error generating i18n types:", error);
  process.exit(1);
}
