name: PR Quality Checks

on:
  pull_request:
    branches:
      - main
      - develop
      - "release/**"

permissions:
  contents: read

jobs:
  check-skip:
    name: Check if duplicate run
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - name: Skip duplicate runs
        id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cancel_others: false
          skip_after_successful_duplicate: true

  quality-checks:
    name: Typecheck, Lint, and Unit Test
    needs: check-skip
    if: needs.check-skip.outputs.should_skip != 'true' && github.repository == 'KotonoSora/nara-vite-react-boilerplate'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Bun cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run TypeScript typecheck
        run: bun run typecheck

      - name: Run ESLint
        run: bun run lint

      - name: Run unit tests
        run: bun run test --run --silent 'passed-only'
