name: PR Quality Checks

on:
  pull_request:
    branches:
      - main
      - develop
      - "release/**"

permissions:
  contents: read

jobs:
  quality-checks:
    name: Typecheck, Lint, and Unit Test
    runs-on: ubuntu-latest
    if: github.repository == 'KotonoSora/nara-vite-react-boilerplate'

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Bun cache
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run TypeScript typecheck
        run: bun run typecheck

      - name: Run ESLint
        run: bun run lint

      - name: Run unit tests
        run: bun run test --run --silent 'passed-only'
