/**
 * Auto-generated language constants
 * Generated from: packages/i18n-locales/src/locales/*
 * DO NOT EDIT THIS FILE MANUALLY - Run 'bun run generate:i18n-types' to regenerate
 */

export const DEFAULT_LANGUAGE = "en" as const;

export const SUPPORTED_LANGUAGES = [
  "ar",
  "en",
  "es",
  "fr",
  "hi",
  "ja",
  "th",
  "vi",
  "zh",
] as const;
